name: ProtectionStones
version: 1.4.3
description: A grief prevention plugin.
authors: [Vik1395,Dragoboss]

depend: [WorldGuard, WorldEdit]
main: me.vik1395.ProtectionStones.Main

commands:
  ps:
    description: Teleports player to a random position within the world border.
    aliases: [protectionstone, protectionstones, pstone]
    usage: /ps help
    Permission: protectionstones